###########################################################
# RELATIVE RISK
#
# Calculate relative risk given coverage details and deaths 
# averted. Then impute relative risk for missing countries
# using GBD covariates.
#
###########################################################

# Variables:
#  - deaths_obs: all cause number of deaths observed in real life
#  - strata_deaths: number of deaths attributable to a disease (used for GBD predictions)
#  - strata_deaths_averted: model estimated deaths averted
#  - averted: predicted deaths averted using stats model (for countries not in VIMC ??)

# ---------------------------------------------------------
# Parent function to impute relative risk for all disease-vaccine combinations
# Called by: launch.R, main.R (and other launch-style scripts)
# ---------------------------------------------------------
run_relative_risk <- function(source = c("vimc", "gbd"), activity = "routine") {
  
  # Options for source: "vimc", "gbd", or any combination of
  # Options for activity: "routine", "campaign", "combined" or any combination of
  
  # Only continue if specified by do_step
  if (!is.element(1, o$do_step)) return()
  
  message("* Calculating relative risk")
  
  # Load all tables up front (see db_utils.R)
  load_tables("coverage", "all_deaths", "vimc_impact", "gbd_strata_deaths", "wpp_input")
  
  # Filter out non-routinte activities if desired
  all_strata = d_v_at_table %>%
    left_join(y  = disease_table, 
              by = "disease") %>%
    filter(source        %in% !!source, 
           activity_type %in% !!activity) %>%
    select(-disease_id, -disease_name)
  
  
  
  all_strata = all_strata[17, ]
  
  
  
  # Shorthand for all strata IDs to work with
  strata_ids = all_strata$d_v_at_id
  
  # Load strata parameters generated by prep_params()
  #
  # NOTE: alpha and beta always 1 (unsure what these are actually doing)
  all_params = jsonlite::fromJSON(o$pth$parameters)  # Strcture: d, v, at, alpha, beta, age_knots
  
  # Calculate and impute relative risk for each strata
  #
  # NOTE: Result for each strata saved to file (in o$pth$relative_risk)
  lapply(strata_ids, function(id)
    impute_strata_rr(all_strata, all_params, id))
  
  message(" - Concatenating relative risk results")
  
  browser()
  
  # Bind all stratas into single datatable
  rr_dt = lapply(strata_ids, load_rr) %>%
    rbindlist(fill = TRUE)
  
  # Save relative risk calculations and predictions to file
  save_file(rr_dt, o$pth$relative_risk, "relative_risk")
  
  # ---- Plot diagnostics ----
  
  # Check flag
  if (o$plot_diagnostics) {
    
    message(" - Plotting diagnostics")
    
    # TODO: Where is this used ??
    # fit_summary <- summarize_fit(rr_dt)  
    
    plot_strata_fit(rr_dt)
  }
}

# ---------------------------------------------------------
# Impute relative risk for a given disease-vaccine combination (aka strata)
# Called by: run_relative_risk()
# ---------------------------------------------------------
impute_strata_rr <- function(all_strata, all_params, strata_id) {
  
  # Details of this strata
  strata = all_strata[d_v_at_id == strata_id]
  params = all_params[[strata_id]]
  
  # Display strata details
  message(" - Strata ID: ", strata_id,       "\n",
          "  > Disease: ",  strata$disease , "\n",
          "  > Vaccine: ",  strata$vaccine,  "\n", 
          "  > Activity: ", strata$activity_type)
  
  # Prepare for relative risk calculation
  dt = prep_rr(strata, params)
  
  browser()
  
  # Append country-specific covariates (eg social-economic index) from GBD
  dt = merge_rr_covariates(dt)
  
  # Return trivial datatable if no valid relative risk results
  if (nrow(dt[rr > 0 & rr < 1]) == 0)
    return(data.table())
  
  # ---- Fit a model to predict relative risk ----
  
  # @Austin: Why binomial when predictor is continuous?
  
  # Fit a binomial GLM for relative risk using GBD covariates
  fit = glm(formula = rr ~ haqi + sdi + year + mx + 
               splines::bs(age, knots = params$age_knots),
             data    = dt[rr > 0 & rr < 1],
             family  = "binomial")
  
  # Predict relative risk
  dt[, pred := predict(fit, dt)]
  
  # Transform these predictions (?? Not sure what's happening here ??)
  # For floating point precision
  dt[, pred_rr := ifelse(pred > 0, 1 / (1 + exp(-pred)), exp(pred) / (exp(pred) + 1))]
  
  # Remove covariates
  dt[, c("pred", "haqi", "sdi", "mx") := NULL]
  dt[, d_v_at_id := strata_id]
  
  # browser()  # This function is the inverse of vimc_rr() ??
  
  dt[, averted := get_averted_deaths(deaths_obs, coverage, pred_rr, params$alpha)]
  
  # Save result to file
  save_file(dt, o$pth$relative_risk, paste0("relative_risk_id", strata_id))
}

# ---------------------------------------------------------
# Prepare relative risk calculation for given strata
# Called by: impute_strata_rr()
# ---------------------------------------------------------
prep_rr <- function(strata, params) {
  
  # ---- Extract strata details ----
  
  # Shorthand for strata ID
  strata_id = strata$d_v_at_id
  
  # Vaccine-actitvity ID
  #
  # NOTE: Not necessarily same as d_v_at_id (eg DTP3 single vaccine for multiple diseases)
  v_at_id = v_at_table %>% 
    filter(vaccine       == strata$vaccine, 
           activity_type == strata$activity_type) %>%
    pull(v_at_id)
  
  # ---- Load data ----
  
  # TODO: Consistent order of columns and sorting (country, year, age, sex_id, ...)?
  
  message("  > Impact source: ", toupper(strata$source))
  
  # For VIMC diseases
  if (strata$source == "vimc") {
    
    # For VIMC diseases, we can take deaths averted directly
    dt = vimc_impact %>%
      filter(d_v_at_id == strata$d_v_at_id) %>%  # Only this strata
      # Append variable...
      mutate(sex_id        = 3,  # ID of both genders combined
             strata_deaths = NA, # Placeholder: to be calculated
             .before       = deaths_averted) %>%  
      # Deaths averted is what has been calculated already...
      rename(strata_deaths_averted = deaths_averted)
    
    # Observed deaths (sum over gender)
    deaths = all_deaths %>%
      # Deal with 'NA' deaths being stored as character...
      mutate(deaths = ifelse(deaths == "NA", 0, deaths), 
             deaths = as.numeric(deaths)) %>%
      # Sum over gender...
      group_by(country, year, age) %>%
      summarise(deaths = sum(deaths)) %>%
      ungroup() %>%
      mutate(sex_id = 3, .before = deaths) %>%  # ID of both genders combined
      # These are our 'observed' deaths...
      rename(deaths_obs = deaths) %>%
      as.data.table()
  }
  
  # For GBD diseases
  if (strata$source == "gbd") {
    
    # For GBD diseases, start with deaths attributable to each disease
    dt = gbd_strata_deaths %>%
      filter(d_v_at_id == strata$d_v_at_id) %>%  # Only this strata
      left_join(y  = loc_table[, .(location_id, country = location_iso3)],
                by = "location_id") %>%
      select(country, d_v_at_id, year, age, sex_id, value) %>%
      # Deaths observed for this disease...
      rename(strata_deaths = value) %>%
      mutate(strata_deaths_averted = NA)  # Placeholder: to be calculated
    
    # Observed deaths (genders seperate)
    deaths = all_deaths %>%
      # Deal with 'NA' deaths being stored as character...
      mutate(deaths = ifelse(deaths == "NA", 0, deaths), 
             deaths = as.numeric(deaths)) %>%
      # These are our 'observed' deaths...
      rename(deaths_obs = deaths)
  }
  
  # Merge vaccine impact deaths with all cause observed deaths
  dt %<>% 
    inner_join(deaths, by = c("country", "year", "age", "sex_id")) %>% # Or right_join ??
    arrange(country, year, age)
  
  # ---- Total vaccine coverage by cohort ----
  
  # @Austin: I think total_coverage() should be handling the different activities. 
  # Meaning we shouldn't first filter by v_at_id. Thoughts?
  
  # xxxx
  # tot_cov = 
  strata_cov = coverage %>%
    filter(v_at_id == !!v_at_id,  # Coverage is per vaccine, not per strata
           year %in% o$analysis_years)
  
  # Total coverage: version 1
  # tictoc::tic("v1")
  tot_cov = strata_cov %>% total_coverage()  # See total_coverage.R
  # time_clock1 = tictoc::toc()
  
  # An attempt to make this calculation cleaner and faster...
  
  # # Total coverage: version 2
  # tictoc::tic("v2")
  # tot_cov2 = strata_cov %>% total_coverage2()  # See total_coverage.R
  # time_clock2 = tictoc::toc()
  # 
  # # Check these are identical...
  # check_dt = tot_cov2 %>%
  #   mutate(activity_type = strata$activity_type) %>%
  #   rename(value2 = value) %>%
  #   left_join(y  = tot_cov, 
  #             by = c("year", "age", "country", "sex_id", "vaccine", "activity_type")) %>%
  #   mutate(diff_value = abs(value - value2)) %>%
  #   filter(diff_value > 1e-8)
  # 
  # # Throw an error if any differences
  # if (nrow(check_dt) > 0)
  #   stop("Discrepancy between v1 and v2 functions")
  
  # Gender-related coverage issues...
  
  # @Austin: This feels like a big assumption, especially for vaccines like HPV, could we get
  # gender-specific outcomes from VIMC? Perhaps this is what you meant by your TODO comment?
  
  # Mean coverage across both age groups
  #
  # TODO: This collapsing of sex should go away (AC)
  cov_dt <- tot_cov[, .(coverage = mean(value)), by = .(country, year, age)]
  cov_dt[, sex_id := 3]
  
  # cov_dt2 = copy(cov_dt)
  
  # Reapply coverage for both age groups
  if (strata$source == "gbd")
    cov_dt <- rbindlist(lapply(1:2, function(s) copy(cov_dt)[, sex_id := s]))
  
  # Join coverage details to effect datatable
  dt <- merge(dt, cov_dt, by = c("country", "year", "age", "sex_id")) #, all = T) # Should be full join ??
  
  # plot_fn = function(dt) {
  #   g = ggplot(dt[coverage > 0 & country == "AFG"]) +
  #     aes(x = year, y = coverage, colour = age, shape = as.factor(sex_id)) +
  #     geom_point() +
  #     facet_grid(sex_id~country) +
  #     ylim(c(0, 1))
  # }
  # 
  # g0 = plot_fn(tot_cov %>% rename(coverage = value))
  # g1 = plot_fn(cov_dt)
  # g2 = plot_fn(cov_dt2)
  
  # browser()
  
  # ---- Calcualte relative risk ----
  
  # Only needed for non-VIMC vaccines... otherwise NA
  #
  # NOTE: Is the column really necessary?
  #       As it's only a single value it can be assigned to a single variable?
  # dt[, efficacy := merge(strata, efficacy)$mean]
  
  # Calcualte relative risk: for VIMC and non-VIMC diseases
  if (strata$source == "vimc") dt %<>% vimc_rr(params)
  if (strata$source == "gbd")  dt %<>% gbd_rr(params, strata)
  
  browser()
  
  # Reorder columns of output
  #
  # TODO: This shouldn't be necessary
  out_dt <- dt[, .(country, age, year, d_v_at_id, deaths_obs,
                   strata_deaths_averted, strata_deaths, coverage, rr)]
  
  # Perform sanity checks on relative risk calculations
  check_rr(out_dt)
  
  return(out_dt)
}

# ---------------------------------------------------------
# Calculate relative risk for VIMC disease
# Called by: prep_rr()
# ---------------------------------------------------------
vimc_rr <- function(dt, p) {
  
  # Relative risk tends to 1 as coverage tends to 1, could be negative
  #
  # rr = (o - (a * (1 - c^alpha) / c^alpha)) / (o + a)
  #
  # where:
  #   o = deaths observed
  #   a = deaths averted from vaccine
  #   c = coverage
  
  browser()
  
  # Calculate relative risk
  out_dt <- copy(dt)
  out_dt[coverage > 0, rr := (deaths_obs - (strata_deaths_averted *
                                              (1 - coverage ^ p$alpha) / coverage ^ p$alpha)) /
           (deaths_obs + strata_deaths_averted)]
  
  return(out_dt[])
}

# ---------------------------------------------------------
# Calculate relative risk for GBD disease
# Called by: prep_rr()
# ---------------------------------------------------------
gbd_rr <- function(dt, p, strata) {
  
  # Relative risk tends to 1 as coverage tends to 1, could be negative
  #
  # rr = (o - d + w * (1 - e*beta)) / (o - d + w)
  #
  # where:
  #   o = deaths observed
  #   d = deaths attributable to this disease
  #   w = deaths estimated without a vaccine
  #   e = vaccine efficacy
  # 
  # Note that w - d equivalent to a (ie deaths averted from vimc_rr function)
  
  browser()
  
  # Vaccine efficacy
  strata_efficacy = efficacy %>%
    filter(disease == strata$disease, 
           vaccine == strata$vaccine) %>%
    pull(mean)
  
  # Number of deaths expected without vaccination ??
  out_dt <- copy(dt)
  out_dt[coverage > 0, deaths_no := strata_deaths /
           (1 - p$beta * strata_efficacy * coverage ^ p$alpha)]
  
  # Calculate relative risk
  out_dt[coverage > 0, rr :=
           (deaths_obs - strata_deaths + (1 - p$beta * strata_efficacy) * deaths_no) /
           (deaths_obs - strata_deaths + deaths_no)]
  
  # Remove now-redundant parameter
  out_dt[, deaths_no := NULL]
  
  return(out_dt[])
}

# ---------------------------------------------------------
# Perform sanity checks on relative risk calculations
# Called by: prep_rr()
# ---------------------------------------------------------
check_rr <- function(dt) {
  
  # Look for missing coverage where deaths averted are non-zero
  if (nrow(dt[coverage == 0 & strata_deaths_averted > 0]) > 0) {
    
    # Proportion of cases
    prop <- round(nrow(dt[coverage == 0 & strata_deaths_averted > 0]) /
                    nrow(dt[strata_deaths_averted > 0]) * 100, 2)
    
    # Throw warning
    warning("Missing coverage in ", prop,
            "% of country-age-years with deaths averted")
  }
  
  # Check for non-sensical numbers
  if (any(range(dt[!is.na(rr)]$rr) < 0 | range(dt[!is.na(rr)]$rr) > 1)) {
    
    # Proportion of cases
    prop <- round(nrow(dt[coverage > 0 & (rr < 0 | rr > 1)]) /
                    nrow(dt) * 100, 2)
    
    # Throw warning
    warning("Over 1 or less than 0 mortality reduction in ", prop,
            "% of country-age-years")
  }
}

# ---------------------------------------------------------
# Function for loading relative risk of a strata
# Called by: impute_all_rr()
# ---------------------------------------------------------
load_rr = function(id) {
  
  # Attempt to load relative risk result for this strata
  strata_rr = try_load(pth  = o$pth$relative_risk, 
                       file = paste0("relative_risk_id", id), 
                       throw_error = FALSE)  # Set to FALSE to throw only a warning
  
  return(strata_rr)
}

# ---------------------------------------------------------
# Append country-specific covariates (eg social-economic index) from GBD
# Called by: impute_strata_rr()
# ---------------------------------------------------------
merge_rr_covariates <- function(dt) {
  
  # NOTES:
  #  1) WWP stands for 'World Population Prospects'
  #     - nx := Number of people
  #     - mx := ??
  #     - fx := fertility rate
  #     - mig := migration rate
  #  a) The mx in the WPP stands for ???
  #  2) Within the GBD (Global Burden of Disease) data
  #  a) HAQi stands for 'Healthcare Access and Quality index'
  #     See: https://www.healthdata.org/research-article/healthcare-access-and-quality-index-based-mortality-causes-amenable-personal-health
  #  b) SDI stands for 'Socio-demographic Index'
  #     See: https://www.healthdata.org/taxonomy/glossary/socio-demographic-index-sdi
  
  # All countries, years, and ages
  dt = expand_grid(
    country = unique(country_table$country),
    age     = o$data_ages,
    year    = 2000 : 2095) %>% # ?? Why 2095?
    as.data.table() %>%
    merge(dt, by = c("country", "age", "year"), all.x = T)
  
  # Add mortality
  mx_dt <- wpp_input[, .(mx = mean(mx)), by = .(country, year, age)]
  dt <- merge(dt, mx_dt, by = c("country", "age", "year"), all.x = T)
  
  # Add GBD covariates (SDI and HAQi)
  dt <- merge(dt, gbd_cov, by = c("country", "year"), all.x = T)
  
  return(dt)
}

# ---------------------------------------------------------
# Extract averted deaths from relative risk equation
# Called by: impute_strata_rr()
# ---------------------------------------------------------
get_averted_deaths <- function(deaths_obs, coverage, rr, alpha) {
  
  # rr = (o - (a * (1 - c^alpha) / c^alpha)) / (o + a)
  #
  # => a = (o * (1 - rr) * c^alpha) / (1 + (rr - 1) * c^alpha)
  #
  # where:
  #   o = deaths observed
  #   a = deaths averted from vaccine
  #   c = coverage
  
  # Estimate deaths averted given relative risk
  #
  # NOTE: Equation derived by solving vimc_rr for a
  averted_deaths <- deaths_obs * (coverage ^ alpha * (1 - rr) / 
                                    (1 - coverage ^ alpha * (1 - rr)))
  
  return(averted_deaths)
}

